import { AppRole, UserProfile } from '@/types';

export const DEMO_EMAILS: Record<AppRole, string> = {
  fan: 'fan@goalplace256.com',
  athlete: 'athlete@goalplace256.com',
  team_admin: 'team@goalplace256.com',
  league_admin: 'league@goalplace256.com',
  sponsor: 'sponsor@goalplace256.com',
  platform_admin: 'admin@goalplace256.com',
  super_admin: 'superadmin@goalplace256.com',
};

export const MOCK_PROFILES: Record<AppRole, UserProfile> = {
  fan: {
    id: 'mock_fan',
    uid: 'mock_fan_uid',
    email: DEMO_EMAILS.fan,
    name: 'Demo Fan',
    role: 'fan',
    status: 'active',
    points: 120,
    walletBalance: 50000,
    followedAthletes: [],
    followedTeams: [],
    followedLeagues: [],
  },
  athlete: {
    id: 'mock_athlete',
    uid: 'mock_athlete_uid',
    email: DEMO_EMAILS.athlete,
    name: 'Demo Athlete',
    role: 'athlete',
    status: 'active',
    points: 500,
    walletBalance: 200000,
    followedAthletes: [],
    followedTeams: [],
    followedLeagues: [],
  },
  team_admin: {
    id: 'mock_team_admin',
    uid: 'mock_team_uid',
    email: DEMO_EMAILS.team_admin,
    name: 'Demo Team Operator',
    role: 'team_admin',
    status: 'active',
    points: 300,
    walletBalance: 0,
    followedAthletes: [],
    followedTeams: [],
    followedLeagues: [],
  },
  league_admin: {
    id: 'mock_league_admin',
    uid: 'mock_league_uid',
    email: DEMO_EMAILS.league_admin,
    name: 'Demo League Admin',
    role: 'league_admin',
    status: 'active',
    points: 400,
    walletBalance: 0,
    followedAthletes: [],
    followedTeams: [],
    followedLeagues: [],
  },
  sponsor: {
    id: 'mock_sponsor',
    uid: 'mock_sponsor_uid',
    email: DEMO_EMAILS.sponsor,
    name: 'Demo Sponsor',
    role: 'sponsor',
    status: 'active',
    points: 0,
    walletBalance: 5000000,
    followedAthletes: [],
    followedTeams: [],
    followedLeagues: [],
  },
  platform_admin: {
    id: 'mock_admin',
    uid: 'mock_admin_uid',
    email: DEMO_EMAILS.platform_admin,
    name: 'Platform Admin',
    role: 'platform_admin',
    status: 'active',
    points: 0,
    walletBalance: 0,
    followedAthletes: [],
    followedTeams: [],
    followedLeagues: [],
  },
  super_admin: {
    id: 'mock_superadmin',
    uid: 'mock_super_uid',
    email: DEMO_EMAILS.super_admin,
    name: 'Platform Owner',
    role: 'super_admin',
    status: 'active',
    points: 0,
    walletBalance: 0,
    followedAthletes: [],
    followedTeams: [],
    followedLeagues: [],
  },
};
